name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI_XCODE_VER: '/Applications/Xcode_12.2.app/Contents/Developer'

jobs:
  swift-test-ios:
    
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build-Test
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project OCKSample.xcodeproj -scheme OCKSample -destination platform\=iOS\ Simulator,name\=iPhone\ 11\ Pro\ Max build test | xcpretty
    - name: Send codecov
      run: bash <(curl https://codecov.io/bash)
